# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{easy-vimeo}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["slainer68"]
  s.date = %q{2009-12-08}
  s.description = %q{EasyVimeo is an object wrapper around the Ruby Vimeo API to easily upload videos to Vimeo.com}
  s.email = %q{slainer68@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "easy-vimeo.gemspec",
     "lib/easy-vimeo.rb",
     "spec/easy-vimeo_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/slainer68/easy-vimeo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{EasyVimeo is an object wrapper around the Ruby Vimeo API to easily upload videos to Vimeo.com}
  s.test_files = [
    "spec/easy-vimeo_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<vimeo>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<httpclient>, [">= 2.1.5"])
    else
      s.add_dependency(%q<vimeo>, [">= 1.0.0"])
      s.add_dependency(%q<httpclient>, [">= 2.1.5"])
    end
  else
    s.add_dependency(%q<vimeo>, [">= 1.0.0"])
    s.add_dependency(%q<httpclient>, [">= 2.1.5"])
  end
end
